#!/usr/bin/env ruby

require "nutrella"

board_name = Nutrella::TaskBoardName.from_git_branch
board_skeleton_filename = ARGV[0]

Nutrella::Command.new(Dir.home, board_name, board_skeleton_filename).run
